name = "hello_ConformalPrediction"
uuid = "8766381a-aec6-4ee3-8f3e-2b67272cb9b3"
authors = ["Fernando Palafox <fernando.palafox@colorado.edu>"]
version = "0.1.0"

[deps]
ConformalPrediction = "98bfc277-1877-43dc-819b-a3e38c30242f"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
NearestNeighborModels = "636a865e-7cf4-491e-846c-de09b730eb36"
